== Recoverable Errors with Result

* https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html[Recoverable Errors with Result - The Rust Programming Language^]

=== Set up a new project
. Set up a new project, and go to the projects directory.
+
[source,console]
----
$ cargo new --bin chap09
     Created binary (application) `chap09` package
$ cd chap09/
----

=== Opening a file
[source,rust]
.Opening a file
----
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");
}
----

=== Using a match expression to handle the Result variants that might be returned
[source,rust]
.Using a match expression to handle the Result variants that might be returned
----
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
----

=== Matching on Different Errors

[source,rust]
.Handling different kinds of errors in different ways
----
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error)
            }
        },
    };
}
----

[source,console]
----
chap09$ rm hello.txt 
rm: cannot remove 'hello.txt': No such file or directory
chap09$ cargo run --bin file_open_and_match
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/file_open_and_match`
chap09$ ls -l hello.txt 
-rw-r--r-- 1 guest guest 0 May  3 03:36 hello.txt
chap09$ 
----

=== Shortcuts for Panic on Error: unwrap and expect

[source,rust]
----
use std::fs::File;

fn main() {
    let _f = File::open("hello.txt").unwrap();
}
----

[source,console]
----
chap09$ rm hello.txt 
chap09$ cargo run --bin file_open_and_unwrap
   Compiling chap09 v0.1.0 (<path-of-project>/chap09)
    Finished dev [unoptimized + debuginfo] target(s) in 1.36s
     Running `target/debug/file_open_and_unwrap`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/file_open_and_unwrap.rs:4:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
chap09$ 
----

[source,rust]
----
use std::fs::File;

fn main() {
    let _f = File::open("hello.txt").expect("Failed to open hello.txt");
}
----

[source,console]
----
chap09$ cargo run --bin file_open_and_expect
   Compiling chap09 v0.1.0 (<path-of-project>/chap09)
    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
     Running `target/debug/file_open_and_expect`
thread 'main' panicked at 'Failed to open hello.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/file_open_and_expect.rs:4:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
----

=== Propagating Errors
[source,rust]
----
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}

fn main() {
    match read_username_from_file() {
        Ok(str) => println!("str is {}", str),
        Err(error) => panic!("Problem opening the file: {:?}", error)
    };
}
----

[source,console]
----
chap09$ cargo run --bin file_open_and_expect
   Compiling chap09 v0.1.0 (<path-to-project>/chap09)
    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
     Running `target/debug/file_open_and_expect`
thread 'main' panicked at 'Failed to open hello.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/file_open_and_expect.rs:4:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
chap09$ touch src/propagating_errors.rs
chap09$ cargo run --bin propagating_errors
   Compiling chap09 v0.1.0 (<path-to-project>/chap09)
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
     Running `target/debug/propagating_errors`
thread 'main' panicked at 'Problem opening the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/propagating_errors.rs:24:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
chap09$ echo "foo" > hello.txt
chap09$ cargo run --bin propagating_errors
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/propagating_errors`
str is foo

chap09$ 
----

=== A Shortcut for Propagating Errors: the `?` Operator

[source,rust]
----
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}

fn main() {
    match read_username_from_file() {
        Ok(str) => println!("str is {}", str),
        Err(error) => panic!("Problem opening the file: {:?}", error)
    };
}
----

[source,console]
----
chap09$ echo "foo" > hello.txt
chap09$ cargo run --bin file_open_and_qop
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/file_open_and_qop`
str is foo

chap09$ rm hello.txt 
chap09$ cargo run --bin file_open_and_qop
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/file_open_and_qop`
thread 'main' panicked at 'Problem opening the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/file_open_and_qop.rs:15:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
chap09$
----
